var cases = ["Chroma 2 Case", 
             "Chroma 3 Case", 
             "Chroma Case", 
             "Clutch Case", 
             "CS20 Case", 
             "CS:GO Weapon Case", 
             "CS:GO Weapon Case 2", 
             "CS:GO Weapon Case 3", 
             "Danger Zone Case", 
             "Dreams & Nightmares Case", 
             "eSports 2013 Case", 
             "eSports 2013 Winter Case", 
             "eSports 2014 Summer Case", 
             "Falchion Case", 
             "Fracture Case", 
             "Gamma 2 Case", 
             "Gamma Case", 
             "Glove Case", 
             "Horizon Case", 
             "Huntsman Weapon Case", 
             "Operation Bravo Case", 
             "Operation Breakout Weapon Case", 
             "Operation Broken Fang Case", 
             "Operation Hydra Case", 
             "Operation Phoenix Weapon Case", 
             "Operation Riptide Case", 
             "Operation Vanguard Weapon Case", 
             "Operation Wildfire Case", 
             "Prisma 2 Case", 
             "Prisma Case", 
             "Recoil Case", 
             "Revolver Case", 
             "Shadow Case", 
             "Shattered Web Case", 
             "Snakebite Case", 
             "Spectrum 2 Case", 
             "Spectrum Case", 
             "Winter Offensive Weapon Case"];
