var capsules = ["Antwerp 2022 Challengers Autograph Capsule",
                "Antwerp 2022 Challengers Sticker Capsule",
                "Antwerp 2022 Champions Autograph Capsule",
                "Antwerp 2022 Contenders Autograph Capsule",
                "Antwerp 2022 Contenders Sticker Capsule",
                "Antwerp 2022 Legends Autograph Capsule",
                "Antwerp 2022 Legends Sticker Capsule",
                "The Boardroom Sticker Capsule",
                "Battlefield 2042 Sticker Capsule",
                "Stockholm 2021 Challengers Sticker Capsule",
                "Stockholm 2021 Champions Autograph Capsule",
                "Stockholm 2021 Contenders Sticker Capsule",
                "Stockholm 2021 Finalists Autograph Capsule",
                "Stockholm 2021 Legends Sticker Capsule",
                "2021 Community Sticker Capsule",
                "Poorly Drawn Capsule",
                "2020 RMR Challengers",
                "2020 RMR Contenders",
                "2020 RMR Legends",
                "Warhammer 40,000 Sticker Capsule",
                "Half-Life: Alyx Sticker Capsule",
                "Halo Capsule",
                "CS20 Sticker Capsule",
                "Berlin 2019 Legends Autograph Capsule",
                "Berlin 2019 Legends (Holo/Foil)",
                "Berlin 2019 Minor Challengers Autograph Capsule",
                "Berlin 2019 Minor Challengers (Holo/Foil)",
                "Berlin 2019 Returning Challengers Autograph Capsule",
                "Berlin 2019 Returning Challengers (Holo/Foil)",
                "Chicken Capsule",
                "Feral Predators Capsule",
                "Katowice 2019 Legends Autograph Capsule",
                "Katowice 2019 Legends (Holo/Foil)",
                "Katowice 2019 Minor Challengers Autograph Capsule",
                "Katowice 2019 Minor Challengers (Holo/Foil)",
                "Katowice 2019 Returning Challengers Autograph Capsule",
                "Katowice 2019 Returning Challengers (Holo/Foil)",
                "Skill Groups Capsule",
                "London 2018 Legends Autograph Capsule",
                "London 2018 Legends (Holo/Foil)",
                "London 2018 Minor Challengers Autograph Capsule",
                "London 2018 Minor Challengers (Holo/Foil)",
                "London 2018 Returning Challengers Autograph Capsule",
                "London 2018 Returning Challengers (Holo/Foil)",
                "Community Capsule 2018",
                "Boston 2018 Attending Legends Autograph Capsule",
                "Boston 2018 Attending Legends (Holo/Foil)",
                "Boston 2018 Legends Autograph Capsule",
                "Boston 2018 Legends (Holo/Foil)",
                "Boston 2018 Minor Challengers Autograph Capsule",
                "Boston 2018 Minor Challengers with Flash Gaming Autograph Capsule",
                "Boston 2018 Minor Challengers with Flash Gaming (Holo/Foil)",
                "Boston 2018 Minor Challengers (Holo/Foil)",
                "Boston 2018 Returning Challengers Autograph Capsule",
                "Boston 2018 Returning Challengers (Holo/Foil)",
                "Perfect World Sticker Capsule 1",
                "Perfect World Sticker Capsule 2",
                "Krakow 2017 Challengers Autograph Capsule",
                "Krakow 2017 Challengers (Holo/Foil)",
                "Krakow 2017 Legends Autograph Capsule",
                "Krakow 2017 Legends (Holo/Foil)",
                "Atlanta 2017 Challengers (Holo/Foil)",
                "Atlanta 2017 Legends (Holo/Foil)",
                "Autograph Capsule | Challengers (Foil) | Atlanta 2017",
                "Autograph Capsule | Legends (Foil) | Atlanta 2017",
                /* team autos */
                /* rest of tournament capsules */
                "Bestiary Capsule",
                "Sugarface Capsule",
                "Slid3 Capsule",
                "Team Roles Capsule",
                "Pinups Capsule",
                /* rest of community capsules */
               ];
