var passes = ["Antwerp 2022 Viewer Pass",
              "Antwerp 2022 Viewer Pass + 3 Souvenir Tokens",
              "Stockholm 2021 Viewer Pass",
              "Stockholm 2021 Viewer Pass + 3 Souvenir Tokens",
              "Operation Riptide Premium Pass",
              "Operation Broken Fang Premium Pass",
              "Operation Shattered Web Premium Pass",
              "Berlin 2019 Viewer Pass",
              "Berlin 2019 Viewer Pass + 3 Souvenir Tokens",
              "Katowice 2019 Viewer Pass",
              "Operation Hydra Access Pass",
              "Operation Wildfire Access Pass",
              "Operation Bloodhound Access Pass",
              "Operation Vanguard Access Pass",
              "Operation Breakout All Access Pass",
              "Operation Phoenix Pass",
              "Operation Bravo Pass",
              "Operation Payback Pass"];
