var OPbrfa = ["Sticker | Ancient Beast",
              "Sticker | Ancient Beast (Foil)",
              "Sticker | Ancient Marauder",
              "Sticker | Ancient Protector",
              "Sticker | Badge of Service",
              "Sticker | Battle Scarred",
              "Sticker | Battle Scarred (Holo)",
              "Sticker | Broken Fang",
              "Sticker | Broken Fang (Holo)",
              "Sticker | Coiled Strike",
              "Sticker | Coiled Strike (Holo)",
              "Sticker | Enemy Spotted",
              "Sticker | Enemy Spotted (Holo)",
              "Sticker | Stalking Prey",
              "Sticker | Stone Scales",
              "Sticker | Stone Scales (Foil)"];

var recoil = ["Sticker | Hello AK-47",
              "Sticker | Hello AK-47 (Gold)",
              "Sticker | Hello AUG",
              "Sticker | Hello AUG (Gold)",
              "Sticker | Hello AWP",
              "Sticker | Hello AWP (Gold)",
              "Sticker | Hello CZ75-Auto",
              "Sticker | Hello CZ75-Auto (Gold)",
              "Sticker | Hello FAMAS",
              "Sticker | Hello FAMAS (Gold)",
              "Sticker | Hello Galil AR",
              "Sticker | Hello Galil AR (Gold)",
              "Sticker | Hello M4A1-S",
              "Sticker | Hello M4A1-S (Gold)",
              "Sticker | Hello M4A4",
              "Sticker | Hello M4A4 (Gold)",
              "Sticker | Hello MAC-10",
              "Sticker | Hello MAC-10 (Gold)",
              "Sticker | Hello MP7",
              "Sticker | Hello MP7 (Gold)",
              "Sticker | Hello MP9",
              "Sticker | Hello MP9 (Gold)",
              "Sticker | Hello P90",
              "Sticker | Hello P90 (Gold)",
              "Sticker | Hello PP-Bizon",
              "Sticker | Hello PP-Bizon (Gold)",
              "Sticker | Hello SG 553",
              "Sticker | Hello SG 553 (Gold)",
              "Sticker | Hello UMP-45",
              "Sticker | Hello UMP-45 (Gold)",
              "Sticker | Hello XM1014",
              "Sticker | Hello XM1014 (Gold)"];
