var comm21 = ["Sticker | Ace Devil (Foil)",
              "Sticker | Bullet Hell (Foil)",
              "Sticker | Clutch or Kick",
              "Sticker | Cyber Romanov (Holo)",
              "Sticker | Dr. Dazzles",
              "Sticker | Eye Contact (Holo)",
              "Sticker | EZ",
              "Sticker | Fast Banana",
              "Sticker | Handle With Care (Holo)",
              "Sticker | Hard Carry",
              "Sticker | I See You (Holo)",
              "Sticker | Kitted Out",
              "Sticker | Nademan",
              "Sticker | Nice Clutch (Holo)",
              "Sticker | No Time",
              "Sticker | Purrurists (Foil)",
              "Sticker | Retro Leet",
              "Sticker | Runtime (Holo)",
              "Sticker | Speedy T",
              "Sticker | This Is Fine (CT)",
              "Sticker | War"];
